--LESSON 10 #1
--Write a query that displays the CustomerID, first name and last name of all the customers who ordered at least one product 
--with the word "women" in its model name (Production.ProductModel table, Name column) in 2013. The word can appear at the beginning, middle or end. 
--Instructions: Make sure you have included all the relevant tables in the query. Solve it using "exists".

select per.BusinessEntityID as CustomerID, per.FirstName, per.LastName
from Person.Person per
where exists (select *
				from Sales.Customer sc join Sales.SalesOrderHeader soh on sc.CustomerID = soh.CustomerID
												join Sales.SalesOrderDetail sod on soh.SalesOrderID = sod.SalesOrderID
												join Production.Product pp on sod.ProductID = pp.ProductID
												join Production.ProductModel pm on pp.ProductModelID = pm.ProductModelID
				where pm.Name LIKE '%women%' and YEAR(soh.OrderDate) = 2013 and sc.PersonID = per.BusinessEntityID
			)

--LESSON 10 #2
--Continuing from the previous question, use the query and the tools learned in previous lessons to answer how many customers appeared in question 1.

select count(*) as NoOfCustomers
from Person.Person per
where exists (select *
				from Sales.Customer sc join Sales.SalesOrderHeader soh on sc.CustomerID = soh.CustomerID
												join Sales.SalesOrderDetail sod on soh.SalesOrderID = sod.SalesOrderID
												join Production.Product pp on sod.ProductID = pp.ProductID
												join Production.ProductModel pm on pp.ProductModelID = pm.ProductModelID
				where pm.Name LIKE '%women%' and YEAR(soh.OrderDate) = 2013 and sc.PersonID = per.BusinessEntityID
			)

--LESSON 11 #1
--Write a query that shows the salespeople's (SalesPersonID) average annual order amount (from the OrderDate column). First process the data 
--from the Order header table to get the total amount of orders generated by each salesperson in each year. 
--Then calculate the average of the orders per salesperson for each year. Instructions (note all sections):
		--a. Define a CTE that includes the SalesPersonID, year and total orders generated for each year (OrderDate) and salesperson. 
		   --Calculate only for order records that have a SalesPersonID.
		--b. Use the CTE you already defined to display the average amount of sellers' orders for each year.

with SalesCTE as (select SalesPersonID, year(OrderDate) as SaleYear, sum(SubTotal) as TotalYearOrders
					from Sales.SalesOrderHeader
					where SalesPersonID is not Null
					group by SalesPersonID, year(OrderDate))
select SaleYear, avg(TotalYearOrders) as 'Yearly Average Orders per SalesPerson'
from SalesCTE
group by SaleYear